#!/bin/bash

# ========== USER CONFIGURATION ==========
seedname="wannier90"  # file prefix
target_param="dis_froz_max"  # Set this to dis_froz_max, dis_win_max, dis_froz_min, dis_win_min, etc.
template_win="${seedname}.win"
template_script="wannier90_runscript"
files_to_link=("${seedname}.mmn" "${seedname}.amn" "${seedname}.eig")
band_data="${seedname}_band.dat"
submit_cmd="sbatch --qos=high"  # customize this for your HPC system
reference_band="bnd.dat"  # pyw90 reference band file generated by: pyw90 pre band
# ========================================

# === Function 1: Set up folders & optionally submit jobs ===
function generate_dirs_and_inputs() {
  echo "Enter start, end, and step (e.g., 1 10 0.1):"
  read start end step

  echo "Submit jobs automatically after setup? (y/n):"
  read submit_choice

  values=$(awk -v s=$start -v e=$end -v st=$step 'BEGIN { for (i = s; i <= e+1e-8; i += st) printf "%.4f\n", i }')

  folder_index=1
  for val in $values; do
    folder=$(printf "%04d_%s_%s" "$folder_index" "$target_param" "$val")
    if [[ -d "$folder" ]]; then
      echo "⚠️  $folder exists, clearing content..."
      rm -rf "$folder"/*
    else
      mkdir -p "$folder"
    fi

    cp "$template_win" "$folder/"
    cp "$template_script" "$folder/"

    sed -i "s/^$target_param.*/$target_param = $val/" "$folder/$template_win"

    for file in "${files_to_link[@]}"; do
      ln -s ../"$file" "$folder/$file"
    done

    echo "✅ Prepared $folder with $target_param = $val"

    if [[ "$submit_choice" == "y" ]]; then
      (
        cd "$folder" || exit
        $submit_cmd "$template_script"
      )
      echo "🚀 Job submitted in $folder"
    fi

    folder_index=$((folder_index + 1))
  done
}

# === Helper: Plot one Wannier band against the pyw90 reference ===
function plot_one_band() {
  local folder="$1"
  local label="$2"
  local file="$folder/$band_data"
  local out_png="${label}_compare-gnu.png"

  if [[ -f "$file" ]]; then
    plotcmd="\"$file\" using 1:2 with points pointtype 7 pointsize 1.0 lc rgb 'blue' title 'Wannier band'"
    for ((i=2; i<=max_col; i++)); do
      plotcmd+=", \"$reference_band\" using 1:$i with lines lw 2 lc rgb 'black' notitle"
    done

    # set yrange [-4.5:0]
    gnuplot -persist <<EOF
set terminal pngcairo size 1600,1200 enhanced font 'Arial,14'
set output "$out_png"
set title "$label vs pyw90 reference" noenhanced
set xlabel "k-path"
set ylabel "Energy (eV)"
set grid
plot $plotcmd
EOF
    echo "✅ Generated plot: $out_png"
  else
    echo "⚠️  Skipped $folder: file '$band_data' not found"
  fi
}

function prepare_reference_band() {
  if [[ ! -f "$reference_band" ]]; then
    echo "❌ Error: reference band file '$reference_band' not found in current directory."
    return 1
  fi

  max_col=$(awk '{if (NF > max) max=NF} END {print max}' "$reference_band")
}

# === Function 2: Plot band structure comparison for generated scan folders ===
function plot_band() {
  echo "Enter start, end, and step (e.g., 1 10 0.1):"
  read start end step

  prepare_reference_band || return
  values=$(awk -v s=$start -v e=$end -v st=$step 'BEGIN { for (i = s; i <= e+1e-8; i += st) printf "%.4f\n", i }')

  echo "🎨 Plotting Wannier vs pyw90 reference band using gnuplot..."

  folder_index=1
  for val in $values; do
    folder=$(printf "%04d_%s_%s" "$folder_index" "$target_param" "$val")
    plot_one_band "$folder" "$folder"
    folder_index=$((folder_index + 1))
  done
}

# === Function 3: Plot band structure comparison for a specified folder ===
function plot_band_for_folder() {
  echo "Enter folder name containing '$band_data' (e.g., test):"
  read folder

  if [[ ! -d "$folder" ]]; then
    echo "❌ Error: folder '$folder' not found in current directory."
    return
  fi

  prepare_reference_band || return

  echo "🎨 Plotting $folder/$band_data vs pyw90 reference band using gnuplot..."
  plot_one_band "$folder" "$folder"
}

# === MAIN MENU ===
echo "Select a function:"
echo "1. Setup calculation folders and optionally submit jobs"
echo "2. Plot band structure comparisons (Wannier vs pyw90 reference)"
echo "3. Plot one specified folder (e.g., test) vs pyw90 reference"
read -p "Enter choice (1, 2, or 3): " choice

if [[ "$choice" == "1" ]]; then
  generate_dirs_and_inputs
elif [[ "$choice" == "2" ]]; then
  plot_band
elif [[ "$choice" == "3" ]]; then
  plot_band_for_folder
else
  echo "❌ Invalid choice. Exiting."
fi
